### ISSUE TITLE
loading dialog ROI sliders styling

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/agave#103]
## Use Case

ROI slider looks a bit clunky.

## Solution

Loading Dialog_Region of Interest: Make appearance identical to existing designs. If not possible see other notes.

## Alternatives

improve some details of appearance of the sliders: extra lines at L/R edges and top

**Comment by ShrimpCryptid** [comment]
![Image](https://github.com/allen-cell-animated/agave/assets/30200665/8a0f2a91-9852-412c-8597-6e1f33c17a61)

This is not strictly part of this issue but it's possible to flip the min and max sections with (terrifying? hilarious?) results.

**Comment by toloudis** [comment]
@ShrimpCryptid do you have enough context (screenshots or knowledge of the actual drawing problems) to work on it?  There were some things with the way the outlines are drawn around the slider handles and things of that nature, seemingly off-by-1 pixel drawing issues.  The slider is mostly custom drawn in source code.

**Comment by ShrimpCryptid** [comment]
I was planning on styling the sliders like the default numeric sliders, if that's what you were getting at? It sounds like there might be some additional details I'm missing.

**Comment by ShrimpCryptid** [comment]
![image](https://github.com/allen-cell-animated/agave/assets/30200665/2ec28ebd-2fef-4799-8e58-b894ac9a66fa)

Had a call with Travis yesterday! Here's some additional details he requested:
- [ ] Make paddles wider (16px)
- [ ] Remove spinner handles from the boxes
- [ ] Add the color seen in the Figma to the selected track region, if possible
- [ ] Add radius to box corners
- [ ] Fix box dragging behavior
