### ISSUE TITLE
help / resources

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/agave#142]
help menu / about box,  links to online docs, credits/copyright/license,  any help resources like tutorials

**Comment by TravisKroeker** [comment]
This ticket is in part outcome from a comprehensive User Support Discovery. [Link to Miro Board with findings here](https://miro.com/app/board/uXjVMpyjeUs=/?share_link_id=632071778389)

**Summary:**
Add Help section to main toolbar (preliminary designs completed). Potentially includes:
- About section?
- Link to Forum (labeled Questions?)
- Link to AGAVE website (Learn More About AGAVE...)
- Citation Guidance (user request from Forum... in Ux backlog for awhile). Could be direct link to guidance on website or a modal of some sort. Ability to click one button to copy citation?
- Documentation
- Walkthrough tutorial (eventually)

**Comment by toloudis** [comment]
@TravisKroeker the miro board link is not letting me in. Can you unprotect it?

**Comment by TravisKroeker** [comment]
I think I changed the permissions to allow you access but it looks you completed the task anyway.

From: toloudis ***@***.***>
Date: Wednesday, December 13, 2023 at 1:38 PM
To: allen-cell-animated/agave ***@***.***>
Cc: Travis Kroeker ***@***.***>, Mention ***@***.***>
Subject: Re: [allen-cell-animated/agave] help / resources (Issue #142)

@TravisKroeker<https://github.com/TravisKroeker> the miro board link is not letting me in. Can you unprotect it?

**Comment by toloudis** [comment]
@TravisKroeker Yes I found the other board with the actual help dialog design on it, and completed the first version of the Help menu and dialogs.  Any polish/details remaining can go in fresh tickets here.
