### ISSUE TITLE
Issue Building on Linux

### ISSUE THREAD

**Issue by Npikielny** [allen-cell-animated/agave#15]
## Description
I tried building agave on linux using the steps outlined in the README, but I got the following error:

CMake Error at CMakeLists.txt:72 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.

## Environment

I am running Ubuntu 20.04.2.

**Comment by toloudis** [comment]
This is a little bit particular to how (and where) you have installed Qt, but generally, the error message is giving the correct hints.

Setting a Qt5_DIR environment variable (to the directory of your Qt install, something like `~/Qt/5.15.2/gcc_64` ) before running cmake should help.

If you try this, let me know how it goes!

**Comment by toloudis** [comment]
I'll update the README instructions to make this more clear.

**Comment by toloudis** [comment]
This is because those missing libraries are git submodules.  They have to be pulled with one separate step that looks like this:
`git submodule update --init`
That should do the trick, and I'll make sure that goes into the readme also.

**Comment by Npikielny** [comment]
Building worked! I ran the app from agave/build/agave (which I'm not sure is correct), and the gui works, but the shaders failed to compile:
GL_RENDERER: AMD Radeon RX 5700 XT (NAVI10, DRM 3.38.0, 5.8.0-55-generic, LLVM 11.0.0)
QOpenGLShader::compile(Fragment): 0:294(22): error: sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later

**Comment by toloudis** [comment]
Interesting -- I've not seen this error with agave before.   This may have something to do with the OpenGL version that the application requests when initializing. I can probably recommend a code change for you to try on your local copy of the code.

**Comment by Npikielny** [comment]
Sounds great! What do I need to change?

**Comment by toloudis** [comment]
A bit experimental but at this line:
https://github.com/allen-cell-animated/agave/blob/master/renderlib/renderlib.cpp#L26
change the major version to 4 and the minor version to 0 , rebuild and see if the shaders compile again.

**Comment by toloudis** [comment]
4.1 is actually what I am considering for an update, if this works for you.  MacOS supports 4.1 as far back as 2010 macbooks now.

**Comment by toloudis** [comment]
@Npikielny not sure if you tried this change, but I finally have a PR branch in this repo with the 4.1 OpenGL version change.  I'll be merging it in soon but if you'd like to try again, it's the feature/gl-version-41 branch.

**Comment by toloudis** [comment]
I believe AGAVE 1.1 and up should have resolved this issue.
