### ISSUE TITLE
Possible incorrect hardcoded URL for zstd-1.5.6.tar.gz

### ISSUE THREAD

**Issue by crayonstud** [allen-cell-animated/agave#194]
Greetings!

Linux user here (Endeavouros) trying to install agave 3D. It appears that the hardcoded download URL for v1.5.6/zstd-1.5.6.tar.gz is valid but not correct for the expected package download.

The hard-coded URL in the installer (zstd-populate-urlinfo.txt, which is dynamically generated when I run cmake .. - so I can't just manually change the URL) points to: https://github.com/facebook/zstd/archive/v1.5.6.tar.gz

The installer expects an SHA256SUM of 8c29e06cf42aacc1eafc4077ae2ec6c6fcb96a626157e0593d5e82a34fd403c1 but this file's actual SHA256SUM is 30f35f71c1203369dc979ecde0400ffea93c27391bfd2ac5a9715d2173d92ff7. 

Now the correct download URL (from Github) appears to be https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-1.5.6.tar.gz. When that file is downloaded and you run SHA256sum on it, you get the expected hash of 8c29e06cf42aacc1eafc4077ae2ec6c6fcb96a626157e0593d5e82a34fd403c1.

Any suggests as to how I can get this installed?
Am I missing something?

Any assistance would be greatly appreciated. 

Error Message after zstd-1.5.6.tar.gz is downloaded

-- [download 100% complete]
-- verifying file...
       file='/home/USER/GIT/agave/build/_deps/zstd-subbuild/zstd-populate-prefix/src/v1.5.6.tar.gz'
-- SHA256 hash of
    /home/USER/GIT/agave/build/_deps/zstd-subbuild/zstd-populate-prefix/src/v1.5.6.tar.gz
  does not match expected value
    expected: '8c29e06cf42aacc1eafc4077ae2ec6c6fcb96a626157e0593d5e82a34fd403c1'
      actual: '30f35f71c1203369dc979ecde0400ffea93c27391bfd2ac5a9715d2173d92ff7'
-- Hash mismatch, removing...
CMake Error at zstd-subbuild/zstd-populate-prefix/src/zstd-populate-stamp/download-zstd-populate.cmake:162 (message):
  Each download failed!

make[2]: *** [CMakeFiles/zstd-populate.dir/build.make:103: zstd-populate-prefix/src/zstd-populate-stamp/zstd-populate-download] Error 1
make[2]: Leaving directory '/home/USER/GIT/agave/build/_deps/zstd-subbuild'
make[1]: *** [CMakeFiles/Makefile2:86: CMakeFiles/zstd-populate.dir/all] Error 2
make[1]: Leaving directory '/home/USER/GIT/agave/build/_deps/zstd-subbuild'
make: *** [Makefile:94: all] Error 2

CMake Error at /usr/share/cmake/Modules/FetchContent.cmake:1714 (message):
  Build step for zstd failed: 2
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FetchContent.cmake:1854:EVAL:2 (__FetchContent_directPopulate)
  /usr/share/cmake/Modules/FetchContent.cmake:1854 (cmake_language)
  /usr/share/cmake/Modules/FetchContent.cmake:2081 (FetchContent_Populate)
  renderlib/io/CMakeLists.txt:39 (FetchContent_MakeAvailable)

-- Configuring incomplete, errors occurred!

**Comment by toloudis** [comment]
If you take a look at:
https://github.com/allen-cell-animated/agave/blob/main/renderlib/io/CMakeLists.txt#L35
that's where there's an explicit zstd dependency.  I have a new PR which removes this: #195 - maybe try building with that branch?

**Comment by crayonstud** [comment]
Thanks for that! I just changed the URL in the proper CMakeList and all is well. Thanks for this cool software too!

**Comment by toloudis** [comment]
Closing this for now.  Feel free to reopen or make a new issue if you have problems!! And keep an eye out for a new release in coming weeks.
