### ISSUE TITLE
toolbar ux feedback

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/agave#206]
## Use Case

I’m mostly looking for feedback on the new toolbar buttons just above the main 3D viewport.   Load some volume data and then try them all, look at the tooltips etc.  (Some might seem to do nothing unless you have manipulated the view with mouse.)
One thing I have been wondering is if it would be better to have the 6 on-axis view buttons be collapsed into a menu.
Caveats: I provided the button icons only in one color so far, so in dark mode they don’t show up well.  Intending to fix this by providing a “light mode” set of icons.

## Solution

From @TravisKroeker 

* I think I would go ahead and collapse all the on-axis buttons into a dropdown menu as you suggested. Have it activate on click and stay persistent until a user clicks outside the menu. This will allow them to click through the different views quickly without opening the menu each time if they're looking for something in particular. I'd probably try to place a dropdown caret next to the icon you select for the menu.
* Put equal padding between the icons-  whatever padding you have between "right view" and "show/hide axis helper" should work for all of them. I would also add that same padding on the top and bottom of the buttons
* the tooltips are wrapping unnecessarily. The width should be wide enough that these tooltips in particular don't wrap. Consider using a universal width for all tooltips as the others in this app don't seem to wrap the same way either
* The key combinations in the tooltips for on-axis buttons seem like hot keys and I don't fully understand their intent.
* It would be really nice to have hot keys for home and frame view. As a user is manipulating they can quickly reset whenever they need to

@toloudis reply:
Thank you!  This is great feedback.  The tooltips for the on-axis buttons are not supposed to be representing keyboard shortcuts, just telling you which axis this will align the view with. (positive or negative and x or y or z)  So I probably should find some better textual way of indicating that or leave it out.
I agree to adding hotkeys for home and frame.  Maybe the axis hotkeys could be X and shift-X, Y and shift-Y , Z and shift-Z.

**Comment by toloudis** [comment]
@TravisKroeker I'm considering how to collapse the front/back/left/right/top/bottom buttons under a menu.   Since they are command buttons, do you have a recommendation for what icon the menu should have?  I could just use the word "View" without an icon too.

**Comment by TravisKroeker** [comment]
Just tying this up- sorry for the negligence. Still think you should have the dropdown menu button. The icon should just be blank cube without any of the faces filled in, there should be a caret next to the icon.

One other suggestion is to be generous with the padding between the sets of icons and also above and below the icons. I don't think I'm viewing the latest rendition but it looks a little tight. I think 8px probably would do the trick?

Let me know if you have any other questions.

**Comment by toloudis** [comment]
<img width="349" alt="Screenshot 2024-08-29 at 6 35 19 PM" src="https://github.com/user-attachments/assets/18b0804e-c7ee-4c6a-b356-5c52a6c9a47b">

**Comment by TravisKroeker** [comment]
Nice! Maybe bump down the dropdown menu by a couple ticks. A gap of 1 or 2 pixel between by buttons and menus is fairly standard. I would also just round the corners of the menu the same as the buttons for consistency. Otherwise it's great!
