### ISSUE TITLE
Select GPU for use in headless mode 

### ISSUE THREAD

**Issue by dpshepherd** [allen-cell-animated/agave#22]
First off, thanks for this great rendering package! We are enjoying getting started with it.

## Use Case

We have a display GPU and compute GPU, both Nvidia, on our Linux machine (Linux Mint 19). We have AGAVE working using the primary display GPU for both the GUI and headless mode. We would like to use the compute GPU for batch rendering when running `agave --server` because it has more RAM available.

## Solution

A flag to set the GPU device when starting the server or a bit clearer instructions on how to modify the config file to accomplish this when in headless mode.

## Alternatives

Use down-sampled version of the data we want to render so that it fits in GPU RAM.

**Comment by toloudis** [comment]
Thanks for the recommendation here.  I believe I can add some ability to select gpu when running in server mode on Linux. (Likely ONLY in that scenario).  

At worst I can probably do 
`agave --server --gpu 1`

And maybe something like 
`agave --server --list_gpus`
which will give you a list with some info and then you can select an index to pass into `agave --server --gpu my_favorite_gpu`

AGAVE still uses OpenGL and will likely move toward a more modern graphics api like Vulkan which will make this kind of thing easier to deal with right off the bat.

I'll ping this issue when I think there is something workable.  Downsampling data at load time is also a good idea and something we have considered before, but probably a whole different issue.

**Comment by dpshepherd** [comment]
Sounds great, thank you!

I meant that we can downsample our data before loading, not that we expect AGAVE to downsample for us.
