### ISSUE TITLE
Render window updates

### ISSUE THREAD

**Issue by lynwilhelm** [allen-cell-animated/agave#70]
## Use Case

As a group we discussed new UI additions and changes related to render functionality

## Solution

1. Change "save image" to "quick render" and "quick render" to "render" and place them near one another
2. Add checkbox for autosave (default right now)
3. Ratio presets should precede X,Y fields in hierarchy
4. Ratio presets (and dropdown) should default to existing viewport ratio
5. Add ability constrain proportions checkbox (or lock) (checked by default and position should be last in hierarchy of all size options)
6. Need to add a confirmation modal when user clicks cancel render

**Comment by toloudis** [comment]
Note: Associated with code branch feature/render-series

**Comment by toloudis** [comment]
I'll add one more:  
When initially displaying render dialog, show viewport image and use viewport XY dimensions.  Afterward, should use previous settings if possible. (Should I use last-rendered-image or always grab from viewport?)

**Comment by toloudis** [comment]
All, or most, are now incorporated into #72 
I'll close this and we can re-review.  There are certainly bugs and things still to fix.
