### ISSUE TITLE
3d viewport toolbar design

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/agave#95]
### Background

agave toolbar is currently a single "main app" toolbar which comprises a variety of different categories of commands: file loading, file saving, rendering to image file, and viewport camera controls. 

### User needs statement(s)
As a use, I want to easier and clearer contextual commands, so that I can manipulate the 3D viewport more easily.

### Size
m

### Requirements
separate toolbar associated with main 3d view, different from main app toolbar.  icon buttons.  compare button controls with simularium and website-3d-cell-viewer and ensure a comprehensive collection of single click commands that 80% of users would use on a regular basis.  

### Deliverables
design document for a 3d viewport toolbar, highlighting which buttons are new vs old, and any new behaviors that differ from existing.

### Stakeholder(s)
@toloudis 

### Timeline
TBD

**Comment by ShrimpCryptid** [comment]
Link to Google Sheet spec:
https://docs.google.com/spreadsheets/d/1TlwpEsdmDqu3GrRHU47PrAmNvCZZYXnGyfFfy6l1J8g

**Comment by toloudis** [comment]
> Link to Google Sheet spec: https://docs.google.com/spreadsheets/d/1TlwpEsdmDqu3GrRHU47PrAmNvCZZYXnGyfFfy6l1J8g

#135

**Comment by toloudis** [comment]
implementation started in #192
